### ISSUE TITLE
"Unkown noparam instruction"

### ISSUE THREAD

**Issue by ghost** [ccldev/use-ccl#1]
`var System = (java.lang.System);`

`var print = System.out.print;`
`var println = System.out.println;`
`var log = println;`

`var File = (java.io.File);`

`var Boolean = (java.lang.Boolean);`
`var true = Boolean.TRUE;`
`var false = Boolean.FALSE;`

`var Scanner = (java.util.Scanner);`
`var scanner = Scanner(System.in);`
`var read = scanner.nextLine;`

`def add(s1, s2){`
   `return s1("concat")(s2);`
`}`

`var s1 = read();`
`var s2 = read();`

`var result = add(s1,s2);`
`var res = add("Result: ", result);`
`log(res);`

Die obigen Funktionen sind eigentlich `#include lib.cl`.

Zu:
`var result = add(s1,s2);
var res = add("Result: ", result);
log(res);`
sollte egt. `log(add("Result: ", add(s1,s2)));` sein 

Kommt bei log, print, println, System.out.print etc.:

`a` (INPUT)
`b` (INPUT)
`Exception in thread "main" ccl.iface.exec.CclError: Execution Error at line [115]: get`
     `at ccl.exec.mnemo.MnemoInterpreter.execution(MnemoInterpreter.java:63)`
     `at ccl.exec.mnemo.MnemoInterpreter.act(MnemoInterpreter.java:42)`
     `at ccl.dev.test.TEST.main(TEST.java:36)`
`Caused by: java.lang.RuntimeException: UNKNOWN NOPARAM INSTRUCTION get`
     `at ccl.exec.mnemo.MnemoExecuter.evalWithoutParam(MnemoExecuter.java:49)`
     `at ccl.exec.mnemo.MnemoInterpreter.evalLine(MnemoInterpreter.java:76)`
      `at ccl.exec.mnemo.MnemoInterpreter.execution(MnemoInterpreter.java:60)`
      `... 2 more`

`

**Comment by NetLamp-Y** [comment]
Oh, scheinbar ist der Doppelpunkt innerhalb des Strings das Problem. Ich werde versuchen den Fehler bald zu beheben. Wenn du den Doppelpunkt bei der vorletzten Zeile wegnimmst geht es, oder?

**Comment by NetLamp-Y** [comment]
So, der Bug ist behoben (bzw. das Feature eingebaut). Wenn du den Code mit der neuen Version (0.2.2) ausführst, bekommst du trotzdem weiterhin eine Fehlermeldung. Du kannst Doppelpunkte aber folgendermaßen verwenden:
`"Doppelpunkt \: Toll oder?"`
Das gibt folgendes aus:
`Doppelpunkt : Toll oder`

Und noch als kurzer hinweis: Leerzeichen am Ende eines Strings funktionieren ebenfalls meist nicht. Du solltest stattdessen das neue "Tabulator-Zeichen" verwenden. (`\t`) Folgendes sollte funktionieren:

```
var System = (java.lang.System);

var print = System.out.print;
var println = System.out.println;
var log = println;

var File = (java.io.File);

var Boolean = (java.lang.Boolean);
var true = Boolean.TRUE;
var false = Boolean.FALSE;

var Scanner = (java.util.Scanner);
var scanner = Scanner(System.in);
var read = scanner.nextLine;

def add(s1, s2){
return s1("concat")(s2);
}

var s1 = read();
var s2 = read();

var res = add("Result\:\t", add(s1,s2));
log(res);
```

Nochmals danke, dass du so viel testest :+1:

**Comment by ghost** [comment]
Nice!
Garkein Ding!
